---
Layout/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

require:
  - chefstyle

AllCops:
  TargetRubyVersion: 3.1
  Include:
    - "**/*.rb"
  Exclude:
    - "vendor/**/*"
    - "spec/**/*"
