---
name: "Lint Unit"

"on":
  pull_request:

jobs:
  lint-unit:
    uses: test-kitchen/.github/.github/workflows/lint-unit.yml@main

  pre-release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: ruby
          package-name: kitchen-hyperv
          version-file: lib/kitchen/driver/hyperv_version.rb
          token: ${{ secrets.PUBLISH_WORKFLOW_TOKEN }}
          signoff: "Dan Webb <dan.webb@damacus.io>"
          changelog-notes-type: github
          prerelease: true
