---
"on":
  push:
    branches: [main]

name: Release
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: ruby
          package-name: kitchen-hyperv
          version-file: lib/kitchen/driver/hyperv_version.rb
          token: ${{ secrets.PUBLISH_WORKFLOW_TOKEN }}
          signoff: "Dan Webb <dan.webb@damacus.io>"
          changelog-notes-type: github

      - name: Build and publish to GitHub Package
        if: ${{ steps.release.outputs.release_created }}
        uses: actionshub/publish-gem-to-github@v1.0.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ secrets.OWNER }}

      - name: Build and publish to RubyGems
        if: ${{ steps.release.outputs.release_created }}
        uses: actionshub/publish-gem-to-rubygems@v1.0.3
        with:
          api_key: ${{ secrets.RUBYGEMS_API_KEY }}
